// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token  string `json:"token"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}

type Menu struct {
	Id        int64    `json:"id,optional"`
	Pid       int64    `json:"pid"`
	Type      uint8    `json:"type"`
	Path      string   `json:"path,optional"`
	Name      string   `json:"name,optional"`
	Perms     string   `json:"perms,optional"`
	Sort      int64    `json:"sort,optional"`
	Redirect  string   `json:"redirect,optional"`
	Component string   `json:"component,optional"`
	Meta      MenuMeta `json:"meta"`
	Children  []*Menu  `json:"children,optional"`
}

type MenuMeta struct {
	Icon        string `json:"icon,optional"`
	Title       string `json:"title"`
	ActiveMenu  string `json:"activeMenu,optional"`
	IsLink      string `json:"isLink,optional"`
	IsHide      uint8  `json:"isHide"`
	IsFull      uint8  `json:"isFull"`
	IsAffix     uint8  `json:"isAffix"`
	IsKeepAlive uint8  `json:"isKeepAlive"`
}

type GetMenuListRequest struct {
	Title string `form:"title,optional"`
	Name  string `form:"name,optional"`
}

type DestroyMenuRequest struct {
	Id int64 `form:"id"`
}

type SysRole struct {
	Id        int64  `json:"id,optional"`
	Name      string `json:"name"`
	UniqueKey string `json:"uniqueKey"`
	Remark    string `json:"remark,optional"`
	MenuIds   string `json:"menuIds"`
	Status    uint8  `json:"status"`
	CreatedAt string `json:"createdAt,optional" form:"-"`
	UpdatedAt string `json:"updatedAt,optional" form:"-"`
}

type GetRoleListRequest struct {
	PaginationRequest
	Name      string `form:"name,optional"`
	UniqueKey string `form:"uniqueKey,optional"`
}

type GetRoleListResponse struct {
	PaginationResponse
	List []*SysRole `json:"list"`
}

type DestroyRoleRequest struct {
	Id int64 `form:"id"`
}

type PaginationRequest struct {
	PageNum  int64 `form:"pageNum"  validate:"number,gte=1"  label:"页数"`
	PageSize int64 `form:"pageSize" validate:"number,gte=1"  label:"条数"`
}

type PaginationResponse struct {
	PageNum  int64 `json:"pageNum"`
	PageSize int64 `json:"pageSize"`
	Total    int64 `json:"total"`
}

type ChangeStatusRequest struct {
	Id     int64 `json:"id"`
	Status uint8 `json:"status"`
}
