// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"chenxi/app/usercenter/internal/logic"
	"chenxi/app/usercenter/internal/svc"
	"chenxi/app/usercenter/usercenter"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	usercenter.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) GetUserInfo(ctx context.Context, in *usercenter.UserInfoRequest) (*usercenter.UserInfoReply, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
