// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: internal.proto

// proto 包名

package cpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthCache struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenKey   string `protobuf:"bytes,1,opt,name=tokenKey,proto3" json:"tokenKey,omitempty"`
	TokenValue string `protobuf:"bytes,2,opt,name=tokenValue,proto3" json:"tokenValue,omitempty"`
	MemberId   uint32 `protobuf:"varint,3,opt,name=memberId,proto3" json:"memberId,omitempty"`
}

func (x *AuthCache) Reset() {
	*x = AuthCache{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCache) ProtoMessage() {}

func (x *AuthCache) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCache.ProtoReflect.Descriptor instead.
func (*AuthCache) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *AuthCache) GetTokenKey() string {
	if x != nil {
		return x.TokenKey
	}
	return ""
}

func (x *AuthCache) GetTokenValue() string {
	if x != nil {
		return x.TokenValue
	}
	return ""
}

func (x *AuthCache) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

// 活跃等级事件参数
type ActiveLevelEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 事件类型
	Event ActiveLevelEnum `protobuf:"varint,1,opt,name=event,proto3,enum=cpb.ActiveLevelEnum" json:"event,omitempty"`
	// 来源id
	SourceUid uint32 `protobuf:"varint,2,opt,name=sourceUid,proto3" json:"sourceUid,omitempty"`
	// 数量
	Num uint32 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	// 中奖来源类型
	Type WinPrizeRewardSourceTypeEnum `protobuf:"varint,4,opt,name=type,proto3,enum=cpb.WinPrizeRewardSourceTypeEnum" json:"type,omitempty"`
	// 日期
	Ymd string `protobuf:"bytes,5,opt,name=Ymd,proto3" json:"Ymd,omitempty"`
	// 比例
	Rate float32 `protobuf:"fixed32,6,opt,name=rate,proto3" json:"rate,omitempty"`
	// pm
	Pm     uint32 `protobuf:"varint,7,opt,name=pm,proto3" json:"pm,omitempty"`
	Remark string `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	LinkId string `protobuf:"bytes,9,opt,name=linkId,proto3" json:"linkId,omitempty"`
}

func (x *ActiveLevelEvent) Reset() {
	*x = ActiveLevelEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveLevelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveLevelEvent) ProtoMessage() {}

func (x *ActiveLevelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveLevelEvent.ProtoReflect.Descriptor instead.
func (*ActiveLevelEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ActiveLevelEvent) GetEvent() ActiveLevelEnum {
	if x != nil {
		return x.Event
	}
	return ActiveLevelEnum_unknow
}

func (x *ActiveLevelEvent) GetSourceUid() uint32 {
	if x != nil {
		return x.SourceUid
	}
	return 0
}

func (x *ActiveLevelEvent) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ActiveLevelEvent) GetType() WinPrizeRewardSourceTypeEnum {
	if x != nil {
		return x.Type
	}
	return WinPrizeRewardSourceTypeEnum_WinPrizeRewardSourceTypeEnumUnknow
}

func (x *ActiveLevelEvent) GetYmd() string {
	if x != nil {
		return x.Ymd
	}
	return ""
}

func (x *ActiveLevelEvent) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ActiveLevelEvent) GetPm() uint32 {
	if x != nil {
		return x.Pm
	}
	return 0
}

func (x *ActiveLevelEvent) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ActiveLevelEvent) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

var File_internal_proto protoreflect.FileDescriptor

var file_internal_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x63, 0x70, 0x62, 0x1a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x63, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8b, 0x02, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x70, 0x62,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x45, 0x6e, 0x75, 0x6d,
	0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x55, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x57, 0x69, 0x6e, 0x50,
	0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x59, 0x6d, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x59, 0x6d, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x72, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x70, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69,
	0x6e, 0x6b, 0x49, 0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData = file_internal_proto_rawDesc
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_rawDescData)
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_goTypes = []interface{}{
	(*AuthCache)(nil),                 // 0: cpb.AuthCache
	(*ActiveLevelEvent)(nil),          // 1: cpb.ActiveLevelEvent
	(ActiveLevelEnum)(0),              // 2: cpb.ActiveLevelEnum
	(WinPrizeRewardSourceTypeEnum)(0), // 3: cpb.WinPrizeRewardSourceTypeEnum
}
var file_internal_proto_depIdxs = []int32{
	2, // 0: cpb.ActiveLevelEvent.event:type_name -> cpb.ActiveLevelEnum
	3, // 1: cpb.ActiveLevelEvent.type:type_name -> cpb.WinPrizeRewardSourceTypeEnum
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	file_enum_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthCache); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveLevelEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_rawDesc = nil
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
