// Code generated by goctl. DO NOT EDIT.

package gamemodel

import (
	"context"
	"database/sql"
	"strings"
	"time"
	"chenxi/pkg/dao/mysql"
	"chenxi/pkg/model"

	"gorm.io/gorm"
)

type (
	sysUserModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *SysUser) error

		FindOne(ctx context.Context, id uint64) (*SysUser, error)
		Update(ctx context.Context, tx *gorm.DB, data *SysUser) error

		Delete(ctx context.Context, tx *gorm.DB, id uint64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
		Sharding(Sharding model.ISharding) *defaultSysUserModel
		Builder(tx *gorm.DB) *gorm.DB
	}

	defaultSysUserModel struct {
		conn     *gorm.DB
		table    string
		sharding model.ISharding
	}

	SysUser struct {
		Id        uint64         `gorm:"column:id"`
		Account   string         `gorm:"column:account"`    // 账号
		Password  string         `gorm:"column:password"`   // 密码
		Name      string         `gorm:"column:name"`       // 名称
		Avatar    string         `gorm:"column:avatar"`     // 头像
		Status    int64          `gorm:"column:status"`     // 状态: 1=正常 2:锁定
		RoleIds   string         `gorm:"column:role_ids"`   // 角色id
		LoginAt   sql.NullTime   `gorm:"column:login_at"`   // 登录时间
		CreatedAt time.Time      `gorm:"column:created_at"` // 创建时间
		UpdatedAt time.Time      `gorm:"column:updated_at"`
		DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index"`
	}
)

func (SysUser) TableName() string {
	return "`sys_user`"
}

func newSysUserModel(conn *gorm.DB) *defaultSysUserModel {
	return &defaultSysUserModel{
		conn:  conn,
		table: "`sys_user`",
	}
}

func (m *defaultSysUserModel) Sharding(sharding model.ISharding) *defaultSysUserModel {
	m.sharding = sharding
	return m
}

func (m *defaultSysUserModel) Builder(tx *gorm.DB) *gorm.DB {
	return m.scopes(tx).Model(&SysUser{})
}

func (m *defaultSysUserModel) scopes(tx *gorm.DB) *gorm.DB {
	var db = m.conn
	if tx != nil {
		db = tx
	}
	if m.sharding == nil {
		return db
	}
	return db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Table(strings.Trim(m.table, "`") + "_" + m.sharding.GetTableSuffix())
	})
}

func (m *defaultSysUserModel) Insert(ctx context.Context, tx *gorm.DB, data *SysUser) error {
	db := m.scopes(tx)
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultSysUserModel) FindOne(ctx context.Context, id uint64) (*SysUser, error) {
	var resp SysUser
	err := m.scopes(nil).WithContext(ctx).Model(&SysUser{}).Where("`id` = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case mysql.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserModel) Update(ctx context.Context, tx *gorm.DB, data *SysUser) error {
	db := m.scopes(tx)
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultSysUserModel) Delete(ctx context.Context, tx *gorm.DB, id uint64) error {
	db := m.scopes(tx)
	err := db.WithContext(ctx).Delete(&SysUser{}, id).Error

	return err
}

func (m *defaultSysUserModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.scopes(nil).WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var db = m.scopes(tx)
		return fn(db)
	})
}
