// Code generated by goctl. DO NOT EDIT.
package types

type EmptyRequest struct {
}

type LoginRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token      string `json:"token"`
	Id         uint64 `json:"id"`
	Name       string `json:"name"`
	Avatar     string `json:"avatar"`
	GoodNumber string `json:"goodNumber"`
}

type UserInfoResponse struct {
	Id         uint64 `json:"id"`
	Name       string `json:"name"`
	Avatar     string `json:"avatar"`
	GoodNumber string `json:"goodNumber"`
}
